name: dayroutine
description: "DayRoutine - 초개인화 시간표/루틴 관리 앱 v4"
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  firebase_auth: ^6.2.0
  google_sign_in: 6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
