// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJ5O3jLtHD6H23tBKtpTRX5q0sZKDkH0',
    appId: '1:434379766095:web:56dd3f38cc0fc26dceed3a',
    messagingSenderId: '434379766095',
    projectId: 'dayroutine-66593',
    authDomain: 'dayroutine-66593.firebaseapp.com',
    storageBucket: 'dayroutine-66593.firebasestorage.app',
    measurementId: 'G-3PFC5F0NML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy57zzUA3aWRKE_5NguDJLQllhR_a4cqY',
    appId: '1:434379766095:android:52800bf2dc1c37e4ceed3a',
    messagingSenderId: '434379766095',
    projectId: 'dayroutine-66593',
    storageBucket: 'dayroutine-66593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsFvBuB1H2idlPGnhfZf26HYqM9BiQ0fs',
    appId: '1:434379766095:ios:d8b6c79688b7b5aeceed3a',
    messagingSenderId: '434379766095',
    projectId: 'dayroutine-66593',
    storageBucket: 'dayroutine-66593.firebasestorage.app',
    iosBundleId: 'com.example.dayroutine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsFvBuB1H2idlPGnhfZf26HYqM9BiQ0fs',
    appId: '1:434379766095:ios:d8b6c79688b7b5aeceed3a',
    messagingSenderId: '434379766095',
    projectId: 'dayroutine-66593',
    storageBucket: 'dayroutine-66593.firebasestorage.app',
    iosBundleId: 'com.example.dayroutine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIJ5O3jLtHD6H23tBKtpTRX5q0sZKDkH0',
    appId: '1:434379766095:web:c03c0c546206ed83ceed3a',
    messagingSenderId: '434379766095',
    projectId: 'dayroutine-66593',
    authDomain: 'dayroutine-66593.firebaseapp.com',
    storageBucket: 'dayroutine-66593.firebasestorage.app',
    measurementId: 'G-P66CF8DY8P',
  );
}
